[project]
name = "phidata-web-summarizer"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckduckgo-search>=7.5.3",
    "google-cloud-aiplatform>=1.85.0",
    "ollama>=0.4.7",
    "openai>=1.68.2",
    "phidata>=2.7.10",
]
